// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOh9Jcw8DV5qHDU6ksgqDXg8i63ke-zok',
    appId: '1:693247198822:web:f9f90aaab9dcfcc28ccfa7',
    messagingSenderId: '693247198822',
    projectId: 'yazicikurye',
    authDomain: 'yazicikurye.firebaseapp.com',
    storageBucket: 'yazicikurye.appspot.com',
    measurementId: 'G-C2J1G66HLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2TeiKfwmkiPd4mG80QYgxljTPJu7feg',
    appId: '1:693247198822:android:a115fce66bbde8238ccfa7',
    messagingSenderId: '693247198822',
    projectId: 'yazicikurye',
    storageBucket: 'yazicikurye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHutiO6Rq8CNkXA5dIBvaumbYMhzvJI88',
    appId: '1:693247198822:ios:985e13f1c311733c8ccfa7',
    messagingSenderId: '693247198822',
    projectId: 'yazicikurye',
    storageBucket: 'yazicikurye.appspot.com',
    iosClientId: '693247198822-spuo9tvh3t241te3e90sa1i45q6762tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaziciKurye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHutiO6Rq8CNkXA5dIBvaumbYMhzvJI88',
    appId: '1:693247198822:ios:985e13f1c311733c8ccfa7',
    messagingSenderId: '693247198822',
    projectId: 'yazicikurye',
    storageBucket: 'yazicikurye.appspot.com',
    iosClientId: '693247198822-spuo9tvh3t241te3e90sa1i45q6762tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaziciKurye',
  );
}
